# common.mk — shared Make targets for Go projects.
#
# Do not edit this file inside a project: edit it in go-mk and run
# `make update-mk`. Per-project overrides go in the project Makefile,
# BEFORE `include common.mk` — every variable here uses `?=`.

MK_SOURCE ?= https://raw.githubusercontent.com/alex27riva/go-mk/main/common.mk

GO        ?= go
MODULE    ?= $(shell awk '/^module /{print $$2}' go.mod)
BINARY    ?= $(notdir $(MODULE))
CMD_PATH  ?= ./cmd/$(BINARY)
BUILD_DIR ?= bin

VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
COMMIT  ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo none)
DATE    ?= $(shell date -u +%Y-%m-%dT%H:%M:%SZ)

# The target vars must be exported `var` (not `const`) strings in this package,
# or the linker silently injects nothing. Set LDFLAGS_VERSION := to disable.
VERSION_PKG     ?= $(MODULE)/internal/version
LDFLAGS_VERSION ?= -X $(VERSION_PKG).Version=$(VERSION) \
                   -X $(VERSION_PKG).GitCommit=$(COMMIT) \
                   -X $(VERSION_PKG).BuildDate=$(DATE)
EXTRA_LDFLAGS   ?=
LDFLAGS         ?= -s -w $(LDFLAGS_VERSION) $(EXTRA_LDFLAGS)
TEST_FLAGS      ?= -race -count=1

DIST_DIR  ?= dist
PLATFORMS ?= linux/amd64 linux/arm64 darwin/arm64 darwin/amd64 windows/amd64

.DEFAULT_GOAL := help
.PHONY: help build run test cover lint tidy ci clean update-mk dist release

help: ## Show this help
	@grep -hE '^[a-z-]+:.*?## ' $(MAKEFILE_LIST) | sort | \
	 awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-11s\033[0m %s\n", $$1, $$2}'

build: ## Build into bin/
	@mkdir -p $(BUILD_DIR)
	$(GO) build -trimpath -ldflags '$(LDFLAGS)' -o $(BUILD_DIR)/$(BINARY) $(CMD_PATH)

run: ## Run the app (ARGS="...")
	$(GO) run -ldflags '$(LDFLAGS)' $(CMD_PATH) $(ARGS)

test: ## Tests with the race detector
	$(GO) test $(TEST_FLAGS) ./...

cover: ## Coverage summary
	$(GO) test $(TEST_FLAGS) -coverprofile=coverage.out ./...
	@$(GO) tool cover -func=coverage.out | tail -1

lint: ## golangci-lint
	golangci-lint run ./...

tidy: ## Tidy and verify modules
	$(GO) mod tidy && $(GO) mod verify

ci: tidy lint test ## What CI runs

dist: ## Cross-compile for every platform in PLATFORMS
	@rm -rf $(DIST_DIR) && mkdir -p $(DIST_DIR)
	@for p in $(PLATFORMS); do \
	   os=$${p%/*}; arch=$${p#*/}; \
	   out=$(DIST_DIR)/$(BINARY)_$(VERSION)_$${os}_$${arch}; \
	   [ "$$os" = "windows" ] && out=$$out.exe || true; \
	   echo "  -> $$out"; \
	   CGO_ENABLED=0 GOOS=$$os GOARCH=$$arch \
	     $(GO) build -trimpath -ldflags '$(LDFLAGS)' -o $$out $(CMD_PATH) || exit 1; \
	 done

release: dist ## Archive the binaries and write checksums
	@cd $(DIST_DIR) && for f in $(BINARY)_*; do \
	   case $$f in \
	     *.exe) zip -q $${f%.exe}.zip $$f && rm $$f ;; \
	     *)     tar czf $$f.tar.gz $$f && rm $$f ;; \
	   esac; \
	 done; \
	 (sha256sum * 2>/dev/null || shasum -a 256 *) > SHA256SUMS
	@ls -1 $(DIST_DIR)

clean: ## Remove build artefacts
	rm -rf $(BUILD_DIR) $(DIST_DIR) coverage.out

update-mk: ## Fetch the latest common.mk from go-mk
	curl -fsSL $(MK_SOURCE) -o common.mk
	@echo "updated — review 'git diff common.mk' before committing"
